version: '3'
services:
  unms:
    container_name: uisp
    image: nico640/docker-unms:latest
    restart: always
    ports:
      - 3001:80
      - 4431:443
      - 2055:2055/udp
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ./volumes/uisp:/config