services:
  uisp:
    container_name: uisp
    image: nico640/docker-unms:latest
    restart: always
    ports:
      - 3010:80
      - 4430:443
      - 2055:2055/udp
    environment:
      - TZ=Europe/Warsaw
      - PUBLIC_HTTPS_PORT=4430
      - PUBLIC_WS_PORT=4430
    volumes:
      - data:/config
volumes:
  data: